name: ci-package-manager

# This workflow creates a tarball from repo sources.
# It then checks that each of the following package managers is able to install:
# - npm
# - Yarn v1 Classic
# - Yarn (Modern)
# - pnpm
# - bun

on:
    workflow_call:
        inputs:
            pnpm_allow_build_args:
                required: false
                description: The arguments to use for `--allow-build` when installing with pnpm.
                default: ''
                type: string

jobs:
    build-tarball:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repo
              uses: actions/checkout@v7

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"

            - name: Install dependencies
              run: npm install

            - name: Build tarball
              run: npm pack --workspace packages 2>/dev/null || npm pack

            - name: Upload build artifact
              uses: actions/upload-artifact@v7
              with:
                  name: build
                  path: "*.tgz"
                  retention-days: 1

    npm-install:
        needs: build-tarball

        runs-on: ubuntu-latest

        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v8
              with:
                  name: build

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"

            - name: npm install
              run: |
                  npm install ./*.tgz -D

    yarn-v1-install:
        needs: build-tarball

        runs-on: ubuntu-latest

        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v8
              with:
                  name: build

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"

            - name: yarn add
              run: |
                  yarn add ./*.tgz -D

    yarn-install:
        needs: build-tarball

        runs-on: ubuntu-latest

        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v8
              with:
                  name: build

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"

            - name: Install Corepack latest
              run: |
                  npm install -g corepack@latest
                  corepack enable yarn

            - name: yarn add
              run: |
                  corepack use yarn@latest
                  yarn init -p
                  yarn config set npmPreapprovedPackages --json '[
                    "@eslint/*",
                    "eslint",
                    "eslint-config-eslint",
                    "eslint-scope",
                    "eslint-visitor-keys",
                    "espree"
                  ]'
                  yarn add ./*.tgz -D
              env:
                  YARN_ENABLE_IMMUTABLE_INSTALLS: 0 # Allow installs to modify lockfile

    pnpm-install:
        needs: build-tarball

        runs-on: ubuntu-latest

        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v8
              with:
                  name: build

            - name: Install pnpm
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
              with:
                  version: latest

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"

            - name: pnpm add
              run: |
                  cat > .npmrc <<EOT
                  auto-install-peers=true
                  node-linker=hoisted
                  EOT
                  pnpm add ${PNPM_ALLOW_BUILD_ARGS} ./*.tgz -D
              env:
                  PNPM_ALLOW_BUILD_ARGS: ${{ case(inputs.pnpm_allow_build_args != '', format('--allow-build={0}', inputs.pnpm_allow_build_args), '') }}

    bun-install:
        needs: build-tarball

        runs-on: ubuntu-latest

        steps:
            - name: Download build artifact
              uses: actions/download-artifact@v8
              with:
                  name: build

            - name: Set up Bun
              uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

            - name: bun install
              run: |
                  bun install ./*.tgz -D
